### ISSUE TITLE
HibernateSpatial issue

### ISSUE THREAD

**Issue by etj** [geoserver/geofence#97]
`geofence-persistence` will not build due to a missing type 
```
     @Type(type = "org.hibernatespatial.GeometryUserType")
```
(spring ORM will swallow this hibernate error message,  hiding it in a [more generic error](https://github.com/geoserver/geofence/issues/97#issuecomment-349623317)).

That's because the original `hibernate-spatial-h2-geodb` [pom file](https://gist.github.com/etj/e829b3f44fcf28c225898bf62791afb2#file-hibernate-spatial-h2-geodb-1-1-1-pom) included as a dependency `hibernatespatial`.
Around 2016 that artifact was no longer available in any maven repo, so GeoSolutions and Boundless deployed the jar on the respective repos:  
- http://maven.geo-solutions.it/org/hibernatespatial/hibernate-spatial-h2-geodb/1.1.1/ 
- https://repo.boundlessgeo.com/main/org/hibernatespatial/hibernate-spatial-h2-geodb/1.1.1/

Both deploys were created using a default pom file, without dependencies.

So, if in your project you need `hibernate-spatial-h2-geodb` (or `-postgis`, or `-oracle`) and you already have in your local repo the old version, which has the proper dependencies, you do not need to add the `hibernatespatial` dep, but if you use a clean local repo, the new pom file will be downloaded, no dependnecy to the `hibernate-spatial` will be transitively included, and your build will break.

So, in order to fix this issue, you'll need to explicitly add the dependecy
```
        <dependency>
            <groupId>org.hibernatespatial</groupId>
            <artifactId>hibernate-spatial</artifactId>
            <version>1.1.1</version>
        </dependency>
```
to any pom which includes one of the hibernatespatial db specific dialect.

**Comment by etj** [comment]
This is the stacktrace you'll get when using one of the new pom files:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geofenceEntityManagerFactory' defined in class path resource [applicationContext-geofenceDatasource.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: geofence] Unable to build EntityManagerFactory
        at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:306)
        at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:290)
        at org.hibernate.mapping.Property.isValid(Property.java:217)
        at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:463)
        at org.hibernate.mapping.RootClass.validate(RootClass.java:235)
        at org.hibernate.cfg.Configuration.validate(Configuration.java:1332)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1835)
        at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:902)
        at org.springframework.orm.jpa.vendor.SpringHibernateEjbPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateEjbPersistenceProvider.java:51)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
        at org.geoserver.geofence.core.dao.BaseDAOTest.<init>(BaseDAOTest.java:58)
```
